[project]
name = "myai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "fastapi-mcp>=0.3.4",
    "httpx>=0.28.1",
    "uvicorn>=0.34.3",
    "fastapi>=0.115.12",
]
